# Lesson 3: Introduction to Cyber Security Analysis using Python

#### Student Name: Isaac Kone
#### Student ID: 501280479

## Introduction
Regular expressions (regex) are a sequence of characters that define a search pattern. They are primarily used for pattern matching, search, and manipulation of textual data. They provide a powerful and flexible way to search for and manipulate text based on specific patterns and are widely used in programming languages, text editors, command-line tools, and other applications involving textual data.


### Why do I need to know about Regular Expressions (Regex)
Understanding regex can significantly increase your ability to work with text data, automate tasks, and perform more complex analysis. With regex, you can:

 - Find particular strings in large data sets with precision.
 - Clean and reformat data for easier analysis.
 - Efficiently perform find and replace operations in large bodies of text.
 - Validate text to ensure that it's formatted correctly (like phone numbers or emails).

## Lesson Objectives
By the end of this lesson, you will be able to:

 - Understand the basic syntax of regex and how it's used in Python.
 - Work with metacharacters, character classes, and quantifiers.
 - Understand the concept of escaping characters in regex.
 - Use regex to validate, extract, and transform textual data.

Allocate approximately one hour for completion of this lesson.

In this tutorial, we will cover:

 - Basic Syntax
 - Metacharacters and Escaping
 - Character Classes
 - Quantifiers
 - Anchors
 - Grouping and Capturing
 - Alternation
 - Lookaheads and Lookbehinds
 - Modifiers and Flags

We'll also walk through some practical examples of regex usage, such as email validation, phone number extraction, URL extraction, IP address validation, date extraction, and HTML tag removal.

## Basic Syntax of Regular Expressions
In order to use regular expressions effectively, it is important to understand their basic syntax. The syntax of a regular expression is composed of a combination of ordinary and special characters.

Ordinary Characters
Ordinary characters in a regular expression include alphanumeric characters such as 'a', 'b', '1', '2'. When used in a regular expression, these characters simply match themselves exactly. For instance, if we use the regular expression 'abc', it would exactly match the string 'abc' within a larger body of text.

Special Characters
In contrast to ordinary characters, special characters have a reserved status in regular expression syntax and carry unique functions. These special characters help you define more complex and specific search patterns. Below is a brief overview of these special characters:

 - <b>. (dot)</b>: This special character matches any character except for a newline.

 - <b>^ (caret):</b> This character matches the start of the line.

 - <b>$ (dollar):</b> This character matches the end of the line.

 - <b>* (asterisk):</b> This quantifier matches zero or more occurrences of the preceding character.

 - <b>+ (plus):</b> This quantifier matches one or more occurrences of the preceding character.

 - <b>? (question mark):</b> This quantifier matches zero or one occurrence of the preceding character.

 - <b>{ } (curly brackets):</b> These quantifiers specify the exact number of occurrences of the preceding character.

 - <b>[ ] (square brackets):</b> These define a character set, matching any one character enclosed.

 - <b>\ (backslash):</b> This character can serve multiple purposes. It can be used before a special character to indicate that the character should be interpreted literally. It can also introduce various special sequences.

 - <b>| (pipe):</b> This character serves as a logical OR, matching the pattern before or the pattern after it.

 - <b>( ) (parentheses):</b> These are used to define a group, which can be given a quantifier to specify the number of occurrences.

 - **: # = ! < > ' " (colon, hash, equals, exclamation, less than, greater than, single quote, double quote):</b> These are also special characters that have unique meanings in specific contexts within regular expressions.

In the context of regular expressions, knowledge of how and when to use these special characters is fundamental to crafting successful regex patterns. As we explore further, you will see these characters in action and gain a deeper understanding of their functionalities. Let's start with some basic regex syntax. The program below is using regular expression see if a string contains the characters 'abc'.

In [1]:
import re
# Write a regular expression that matches "abc" in the input string
pattern = 'abc'                        
input_string = 'abcdef'
match = re.search(pattern, input_string)
print (f'Match found: {match.group()}')

Match found: abc

Here's a step-by-step explanation:

 - **import re:** This line of code is importing the re module, which provides functions to work with regular expressions.
 
 - **# Write a regular expression that matches "abc" in the input string:** This is a comment, and Python will ignore it.

 - **pattern = "abc":** This line defines a pattern we are looking for, which in this case is simply the string "abc".

 - **input_string = "abcdef":** This line defines the string of text that we want to search within.

 - **match = re.search(pattern, input_string):** This line of code is using the search() function from the re module to look for the pattern "abc" within the input string "abcdef". If the pattern is found, it returns a "match" object. If not, it returns None.

 - **print (f'Match found: {match.group()}'):** This line of code prints the result. It's using the group() method of the match object to get the matched text (which will be "abc"). The output will be "Match found: abc" if the pattern is found in the input string.

In simple terms, this code checks if "abc" appears in the string "abcdef" and prints the result.

## Metacharacters and Escaping
Metacharacters are a specific subset of characters that have been imbued with a distinctive significance in the context of regular expressions. These characters, due to their specialized function, do not represent themselves as literal characters but are instead interpreted as commands or signals that influence the way a pattern is matched in a string.

For instance, take the period or dot <b>('.')</b>. This character, rather than representing a literal period, is recognized as a wildcard in regular expressions. It matches any single character, regardless of what that character may be (with the exception of a newline character in some languages and regex modes).

Another common metacharacter is the asterisk <b>('*')</b>. This character, when used in a regex pattern, does not seek to match a literal asterisk in the text. Instead, it modifies the character or group of characters that immediately precedes it, signifying that zero or more of the preceding character or group should be matched.

While metacharacters serve valuable functions in creating versatile and powerful search patterns, there may be situations where we actually want to find these characters in the text. In these cases, we need to escape the metacharacters, which means to treat them as regular characters. The backslash <b>('\\')</b> is used for this purpose. By placing a backslash before a metacharacter, we are instructing the regular expression engine to treat this character as a literal character, not as a metacharacter with a special meaning. For example, to find a period in a text, we would use <b>'\\.'</b> in our regex pattern.

Now, let's look at this in a practical context with a Python example:

In [2]:
# Pattern to find literal '.'
pattern = "\."
input_string = "abc.def"
match = re.search(pattern, input_string)
print (f'Match found: {match.group()}')

<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'

Match found: .

/tmp/ipykernel_389559/1042828382.py:2: SyntaxWarning: invalid escape sequence '\.'
  pattern = "\."

The above code searches for a specific pattern (a "dot" or period) in a given string of text, and then it prints out whether or not it found the pattern.

 - **pattern = "\.":** This sets the pattern we're looking for to a literal period or "dot" ('.'). The backslash is used because in programming, a dot by itself means "any character," so we need to specify that we're looking for an actual dot.

 - **input_string = "abc.def":** This is the text where we want to look for the pattern. In this case, the text is "abc.def".

 - **match = re.search(pattern, input_string):** This line is doing the actual search. It looks for the pattern (a dot) in the input_string ("abc.def").

 - **print (f'Match found: {match.group()}'):** This line prints out the result. If it found a match (the dot in our input_string), it will print out "Match found: .", indicating that the dot was indeed found in the text.

So, in simple terms, this code is like a game of "Where's Waldo?" but for a dot in a specific text. It looks for the dot and then tells you if it found it.

Here's another example:

In [3]:
# A string with periods and asterisks
text = "This sentence contains periods... and asterisks***"

# Here we want to match literal periods and asterisks, so we escape them
pattern = r'\.|\*'

matches = re.findall(pattern, text)
print (f'Matches found: {matches}')

Matches found: ['.', '.', '.', '*', '*', '*']

In the example above, we have a string that contains both periods and asterisks. Our regex pattern <b>'\.|\*'</b> has escaped versions of the period and the asterisk <b>(.</b> and <b>*)</b>, allowing us to match these literal characters in the text. The vertical bar <b>'|'</b> signifies 'OR', so the pattern matches either a period or an asterisk. As a result, all the periods and asterisks in the text are matched and printed out.

## Character Classes
Character Classes are fundamental elements in the syntax of regular expressions, providing flexibility and precision in text pattern matching. Essentially, a character class allows us to define specific sets or ranges of characters that we want to match in a text string.

In the realm of regular expressions, a character class is represented within square brackets <b>[]</b>. The characters placed inside these brackets form the set of characters that we are interested in.

For instance, <b>[a-z]</b> is a character class. This particular class matches any single lowercase letter from <b>a</b> to <b>z</b>. The hyphen - between <b>a</b> and <b>z</b> denotes a range, indicating that any character that falls within this range (in this case, the English lowercase letters) is a match.

Another example is <b>\d</b>, a special character class. In the syntax of regular expressions, <b>\d</b> is a shorthand character class that matches any single digit from <b>0</b> to <b>9</b>.

Now, let's put this into practice with a Python code snippet. We'll use the re module in Python, which provides support for regular expressions.

In [4]:
# Pattern to find any digit
pattern = "\d"
input_string = "Order 7 apples"
match = re.search(pattern, input_string)
print (f'Match found: {match.group()}')

Match found: 7

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_389559/1209319012.py:2: SyntaxWarning: invalid escape sequence '\d'
  pattern = "\d"

In this code snippet, the <b>findall()</b> function scans the <b>text_string</b> and returns all matches of the pattern, which is <b>\d</b> in our case. The output should be a list of all digits found in the <b>text_string: ['1', '2', '3', '4', '5', '6']</b>.

In conclusion, character classes in regular expressions serve as a powerful tool to define specific patterns that you want to match in a text string. By understanding and using character classes effectively, you can perform highly specialized text searching, validation, and extraction tasks.

## Quantifiers
Quantifiers are special symbols used to define the quantity of characters or groups of characters that we are searching for in a given pattern. They allow us to specify the number of occurrences of a particular character, set of characters, or pattern, providing great flexibility when we want to match complex patterns in a string.

Three common quantifiers in regular expressions are <b>*</b>, <b>+</b>, and <b>?</b>.

<blockquote><b>The asterisk (*):</b> This quantifier denotes zero or more occurrences of the preceding character or group. This means that the character or group may not appear at all, or it may appear multiple times in succession.</blockquote>

<blockquote><b>The plus sign (+):</b> This quantifier signifies one or more occurrences of the preceding character or group. This means that the character or group should appear at least once in the target string.</blockquote>

<blockquote><b>The question mark (?):</b> This quantifier represents zero or one occurrence of the preceding character or group. In other words, the character or group is optional and can appear at most once.</blockquote>

Let's look at a practical example:

In [5]:
# Our target string
text = "The balloon flew away. It floated over the treetops, then disappeared into the clouds."

# Our pattern with quantifiers
pattern = r'fl.*? '

# Let's find all occurrences
matches = re.findall(pattern, text)

# Print matches
print (matches)

['flew ', 'floated ']

In the above example, the regular expression <b>'fl.*? '</b> is looking for patterns that start with <b>'fl'</b> and are followed by any number of any characters (denoted by <b>'.*'</b>). The <b>?</b> after <b>.*</b> makes it non-greedy, i.e., it tries to match as few characters as possible until it encounters a space character.

When we run this script, we will get the following output: <b>['flew ', 'floated ']</b>.

Here, we see that our pattern successfully matched and extracted the words 'flew ' and 'floated ' from the sentence. These words start with <b>'fl'</b> and end when the space character is encountered, which aligns with our regular expression pattern.

## Anchors
An anchor is a special character that does not correspond to an actual character within the text or string you're searching through. Instead, it matches a specific location or position in the text. In essence, anchors are utilized to confine the match to a certain position within the input string. There are two primary anchors used in regex:

<blockquote><b>The caret (^):</b> This anchor is used to indicate the beginning of a line or string. If you prepend <b>'^'</b> to your regular expression pattern, it signifies that the pattern must be found at the very start of the input string.</blockquote>

<blockquote><b>The dollar sign (\\$):</b> Conversely, this anchor symbolizes the end of a line or string. Appending <b>'$'</b> to your regex pattern stipulates that the pattern must be at the absolute end of the string for a match to be found.</blockquote>

To illustrate this concept, consider the following Python code using regular expressions:

In [6]:
# Using the caret (^) anchor
pattern = r'^abc'
string = 'abcdef'
match = re.search(pattern, string)
print ("Match start:", match.start(), "Match end:", match.end()) if match else print("No match found")

# Using the dollar ($) anchor
pattern = r'abc$'
string = 'defabc'
match = re.search(pattern, string)
print ("Match start:", match.start(), "Match end:", match.end()) if match else print("No match found")

Match start: 0 Match end: 3
Match start: 3 Match end: 6

In the first example, the pattern <b>'^abc'</b> will only match strings that start with <b>'abc'</b>. If we pass <b>'abcdef'</b> as the input string, we will get a match from the start position 0 to end position 3 in the string.

In the second example, the pattern <b>'abc$'</b> will only match strings that end with <b>'abc'</b>. If we pass <b>'defabc'</b> as the input string, the match will be found from the start position 3 to end position 6 in the string.

Hence, the anchors help us confine our search to specific positions in the string - the beginning with ^ and the end with $.

# Grouping and Capturing
Grouping and capturing are fundamental aspects of working with regular expressions. They provide a way to treat multiple characters as a single unit, which can be very useful when you want to apply a quantifier to more than one character or when you want to capture the part of the string that matches your grouped expression for further use.

## Introduction to Grouping
The concept of 'grouping' in regular expressions is best understood as a way of defining scope and priority. By using parentheses (), we can indicate that certain parts of our pattern should be treated as a single unit.

For example, let's consider a scenario where we are working with a text string that contains various animal names. We want to match any occurrence of the repeated word pairs 'catcat' or 'dogdog'.

Without grouping, if we were to create a pattern like <b>cat|dog+</b>, this would not give us the desired result. Instead, it would match any occurrence of 'cat', 'dog', 'dogg', 'doggg', etc., because the + quantifier applies only to 'dog', meaning "one or more occurrences of 'dog'".

To correctly implement our intended pattern, we can use grouping:

In [7]:
# Pattern to find any occurrence of 'abc' followed by one or more digits
pattern = "(abc\d+)"
input_string = "abc123 def456 abc789"
matches = re.findall(pattern, input_string)
print (f'Matches found: {matches}')

Matches found: ['abc123', 'abc789']

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
/tmp/ipykernel_389559/3038128428.py:2: SyntaxWarning: invalid escape sequence '\d'
  pattern = "(abc\d+)"

In the pattern <b>(cat|dog)\1</b>, <b>(cat|dog)</b> is a group that matches either 'cat' or 'dog'. The <b>\1</b> is known as a backreference, which matches the same text as most recently matched by the 1st capturing group, i.e., either 'cat' or 'dog'. As a result, this pattern will match 'catcat' or 'dogdog'.

## Introduction to Capturing
While grouping allows us to treat multiple characters as a single unit, <b>'capturing'</b> allows us to extract the portions of the matched text for further use.

Continuing with our previous example, let's say we want to find all repeated word pairs and know exactly which words were repeated. Here's how we can do that:

In [8]:
# Text string for demonstration
text = 'catcat dog dogdog mouse catdog'

# Regex pattern with grouping
pattern = r'(\w+)(?=\1)'

# Find matches
matches = re.findall(pattern, text)

print (matches)

['cat', 'dog']

In the above code:

 - <b>(\w+)</b> matches and captures (due to the parentheses) one or more word characters.
 - <b>(?=\1)</b> is a positive lookahead that asserts what follows is the same text as most recently matched by the first capturing group. In effect, it looks for repetition of the captured group.

Hence, this pattern will correctly match 'cat' in 'catcat' and 'dog' in 'dogdog'.

In summary, grouping and capturing provide powerful tools for both structuring our regex patterns and extracting valuable information from the matched text.

# Alternation
Alternation refers to the mechanism by which we can match multiple different potential patterns within a given string. This gives us the ability to define multiple alternative matches, effectively telling the regular expression engine to match either one pattern or another.

## The OR operator
The symbol used to denote alternation in regular expressions is the pipe character <b>|</b>. This symbol can be considered as the logical OR operator in the context of regular expressions. It signifies that either the pattern on its left side or the pattern on its right side should be considered a match.

### Example
To illustrate this, let's consider a simple example where we would like to match either the word 'cat' or 'dog' in a given string.

Here is how we can construct and use such a regular expression in Python:

In [9]:
pattern = r"cat|dog"
text = "I have a pet cat."

match = re.search(pattern, text)
if match:
    print("Match found:", match.group())
else:
    print("No match found.")

Match found: cat

In this case, the regular expression <b>pattern</b> is defined as <b>r"cat|dog"</b>. This tells the regex engine to match either 'cat' or 'dog'. The string <b>text</b> contains 'cat', so when we execute the <b>re.search()</b> function with <b>pattern</b> and <b>text</b>, we get a match.

If you change <b>text</b> to "I have a pet dog.", you would still get a match. However, if you change <b>text</b> to "I have a pet rabbit.", the program will output "No match found." since neither 'cat' nor 'dog' is found in the string.

## Explanation
In the regular expression pattern <b>r"cat|dog"</b>, the pipe symbol <b>|</b> is used as the alternation operator. The engine will first attempt to match the pattern 'cat'. If that fails, it will then attempt to match 'dog'. If either pattern is found within the string, <b>re.search()</b> will return a match object. If neither pattern is found, <b>re.search()</b> will return <b>None</b>.

Note that the regex engine processes the input from left to right and will stop as soon as a match is found. In a scenario where multiple alternatives can match at the same position in the string, the first alternative specified in the regex pattern will be the one that matches.

## The NOT operator
The caret <b>^</b> symbol has a dual function. It denotes the beginning of a line when used outside square brackets. However, when it's placed inside square brackets at the beginning, it turns into the NOT operator, inversely matching characters.

For instance, if we want to ensure that none of the characters directly preceding the weekday name are letters or numbers, we can use the NOT operator <b>^</b>. The NOT operator negates the character class it is applied to, meaning it matches any character that is not in the specified set.

Consider the following regular expression:
    <b>[^a-zA-Z0-9]Monday</b>

In this regular expression, <b>[^a-zA-Z0-9]</b> is a character class that matches any character that is not a letter <b>a-z</b> or <b>A-Z</b>) or a number <b>0-9</b>. It's then followed by the string "Monday", which matches the exact word.

So, this regular expression will match "Monday" only if it is not immediately preceded by a letter or a number. It could be preceded by a space, a punctuation mark, or the beginning of the string, among other possibilities.

### Example
Let's take a look at an example in Python:

In [10]:
text1 = "2022Monday is a holiday"
text2 = "In 2022, Monday is a holiday"

pattern = r"[^a-zA-Z0-9]Monday"

match1 = re.search(pattern, text1)
match2 = re.search(pattern, text2)

print ("Match in text1: ", bool(match1))
print ("Match in text2: ", bool(match2))

Match in text1:  False
Match in text2:  True

In this example, the regular expression does not match "Monday" in <b>text1</b> because it is preceded by numbers. However, in <b>text2</b>, "Monday" is preceded by a comma and a space, so the regular expression does match "Monday".

Thus, by using the NOT operator (^), you can create more precise regular expressions that match specific patterns in your text data.

# Lookaheads and Lookbehinds
Lookaheads and lookbehinds are types of assertions in regular expressions (regex). They are used to specify a condition that must be met before or after a match, but they don't consume any characters in the string. This means that the regular expression engine does not advance through the string as it checks for a lookahead or lookbehind match. In essence, they enable us to match a pattern based on what precedes (lookbehind) or follows it (lookahead), without including the preceding or following elements in the actual match.

## Lookaheads
Lookaheads are denoted by ?= for positive lookahead and ?! for negative lookahead.

A <b>positive lookahead</b> asserts that what immediately follows the current position in the string is a match for the pattern within the lookahead, but it doesn't consume any characters or move the position of the regex engine in the string.

For instance, consider a scenario where we want to match a number only if it's followed by the word "apples". Here's how we can do it:

In [11]:
text = "5 apples and 4 oranges"
pattern = r'\d(?= apples)'
matches = re.findall(pattern, text)
print (matches)

['5']

In this example, <b>\d</b> matches any digit. The lookahead <b>?= apples</b> specifies that the digit must be followed by the string " apples" to be a match, but " apples" is not part of the match itself.

A <b>negative lookahead</b> asserts that what immediately follows the current position in the string is not a match for the pattern within the lookahead.

In [12]:
text = "5 apples and 4 oranges"
pattern = r'\d(?! apples)'
matches = re.findall(pattern, text)
print (matches)

['4']

In this example, the negative lookahead <b>(?! apples)</b> specifies that the digit must not be followed by " apples" to be a match.

## Lookbehinds
Lookbehinds are denoted by <b>?<=</b> for positive lookbehind and <b>?<!</b> for negative lookbehind.

A <b>positive lookbehind</b> asserts that what immediately precedes the current position in the string is a match for the pattern within the lookbehind, but it doesn't consume any characters or move the position of the regex engine in the string.

For instance, consider a scenario where we want to match a number only if it's preceded by the dollar symbol "$". Here's how we can do it:

In [13]:
text = "$5 and 4"
pattern = r'(?<=\$)\d'
matches = re.findall(pattern, text)
print (matches)

['5']

In this example, <b>\d</b> matches any digit. The lookbehind <b>(?<=\$)</b> specifies that the digit must be preceded by the dollar symbol "$" to be a match, but "$" is not part of the match itself.

A <b>negative lookbehind</b> asserts that what immediately precedes the current position in the string is not a match for the pattern within the lookbehind.

In [14]:
text = "$5 and 4"
pattern = r'(?<!\$)\d'
matches = re.findall(pattern, text)
print (matches)

['4']

In this example, the negative lookbehind <b>(?<!\$)</b> specifies that the digit must not be preceded by the dollar symbol "$" to be a match.

In summary, lookaheads and lookbehinds provide a powerful tool in regex to perform complex pattern matching based on context without including the context in the match. Their use can make your pattern matching tasks more precise and versatile.

# Modifiers and Flags
Modifiers, also known as flags, alter the functionality of the regular expressions to which they are applied. These can significantly influence how your regex pattern matches and handles text. Let's examine two examples: 're.I' and 're.M'.

## Case Insensitive Matching: 're.I'
The 're.I' modifier, also known as the 'IGNORECASE' flag, makes the pattern case insensitive. This means it does not differentiate between uppercase and lowercase letters; a regex pattern with 're.I' will match text regardless of case.

Here's an example:

In [15]:
# Without re.I
pattern = r'hello'
text = 'Hello World'
matches = re.findall(pattern, text)
print (f'Matches found without re.I: {matches}')

# With re.I
matches = re.findall(pattern, text, re.I)
print (f'Matches found with re.I: {matches}')

Matches found without re.I: []
Matches found with re.I: ['Hello']

In the example above, without 're.I', the pattern 'hello' doesn't match 'Hello' because of the difference in case. But when we use 're.I', it matches 'Hello' regardless of the case difference.

## Multiline Matching: 're.M'
The 're.M' modifier, or the 'MULTILINE' flag, influences how '^' and '\\$' special characters operate. Usually, '^' matches the start of a string, and '\\$' matches the end of a string. However, with the 're.M' modifier, '^' will also match after each newline, and '$' will match before each newline.

Here's an example:

In [16]:
# Without re.M
pattern = r'^abc'
text = '123\nabc'
matches = re.findall(pattern, text)
print (f'Matches found without re.M: {matches}')

# With re.M
matches = re.findall(pattern, text, re.M)
print (f'Matches found with re.M: {matches}')

Matches found without re.M: []
Matches found with re.M: ['abc']

In the example above, without 're.M', the pattern '^abc' doesn't match 'abc' because it's not at the start of the string. But when we use 're.M', it matches 'abc' as it is at the start of a line after a newline character.

Understanding these modifiers and how to use them effectively can greatly enhance the flexibility and efficiency of your regular expression usage.

# Practical Application of Regex
The following examples illustrate the application of regex in real-world scenarios, such as email validation, phone number extraction, URL extraction, IP address validation, date extraction, and HTML tag removal:

## Email Validation
When dealing with user input, it is important to verify that the entered data matches certain criteria. For instance, when a user provides an email address, we would like to make sure that it is in a valid format. A typical email address is composed of alphanumeric characters, potentially separated by periods or underscores, followed by an '@' symbol and a domain name.

In Python, the <b>re<b/> module provides a set of functions that allow us to use regular expressions. In the following example, we will use the <b>re.fullmatch()</b> function to check if an email address is valid.

In [17]:
pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
email = "test.email@example.com"
match = re.fullmatch(pattern, email)
print ("Valid" if match else "Invalid")

Valid

This regex pattern <b>^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$</b> can be broken down as follows:

 - <b>^</b> asserts start of a line.
 - <b>[a-zA-Z0-9._%+-]+</b> matches one or more alphanumeric characters, dots, underscores, percent signs, plus signs, or hyphens.
 - <b>@</b> matches the '@' symbol.
 - <b>[a-zA-Z0-9.-]+</b> matches one or more alphanumeric characters, dots, or hyphens (domain name).
 - <b>\</b>. matches the dot before the domain suffix.
 - <b>[a-zA-Z]{2,}</b> matches two or more alphabetic characters (domain suffix).
 - <b>$<b> asserts end of a line

## Phone Number Extraction
TAnother practical application of regex is extracting specific patterns from a larger text body. For example, given a string of text, we might want to extract all phone numbers.

In the following example, we use <b>re.findall()</b> to find all matches of the phone number pattern in the text.

In [18]:
pattern = r'\b\d{3}[-.]?\d{3}[-.]?\d{4}\b'
text = "My phone number is 123-456-7890."
matches = re.findall(pattern, text)
print(f'Matches found: {matches}')

Matches found: ['123-456-7890']

Here, the pattern <b>\b\d{3}[-.]?\d{3}[-.]?\d{4}\b</b> works as follows:

 - <b>\b</b> is a word boundary. It ensures that the pattern we are matching is a standalone word and not part of another word.
 - <b>\d{3}</b> matches any three digits.
 - <b>[-.]?</b> matches either a dash or a period, but this symbol is optional (? means 0 or 1 occurrence).

This pattern repeats for the full phone number format.

## URL Extraction
We might also be interested in extracting URLs from a text. For example, in a web scraping application, it would be helpful to extract all the links in a webpage.

In this example, we use the <b>re.findall()</b> function to find all URLs in the given text.

In [19]:
pattern = r'\bhttps?:\/\/\S+\b'
text = "Check this out: https://www.example.com/sample.pdf"
matches = re.findall(pattern, text)
print (f'Matches found: {matches}')

Matches found: ['https://www.example.com/sample.pdf']

The pattern <b>\bhttps?:\/\/\S+\b</b> can be explained as follows:

 - <b>\b</b> is a word boundary.
 - <b>https?:\/\/</b> matches 'http://' or 'https://'.
 - <b>\S+</b> matches one or more non-whitespace characters.
 - <b>\b</b> is the word boundary again.

## IP Address Validation
An IP address consists of four numbers separated by periods, with each number ranging from 0 to 255. We can validate this using regex.

In [20]:
pattern = r'\b(?:\d{1,3}\.){3}\d{1,3}\b'
ip = "192.168.0.1"
match = re.fullmatch(pattern, ip)
print ("Valid" if match else "Invalid")

Valid

The pattern <b>\b(?:\d{1,3}\.){3}\d{1,3}\b</b> works as follows:

 - <b>\b</b> is a word boundary.
 - <b>(?:\d{1,3}\.){3}</b> matches three sequences of one to three digits followed by a dot.
 - <b>\d{1,3}</b> matches the final one to three digits.
 - <b>\b<b> is the word boundary again.

Note: This pattern does not check if the numbers are between 0 and 255, which would make the pattern considerably more complex.

## Date Extraction
You might need to extract dates from text, and they can come in various formats. Here we match dates in the format of MM/DD/YYYY.

In [21]:
pattern = r'\b\d{2}\/\d{2}\/\d{4}\b'
text = "Today's date is 07/09/2023."
matches = re.findall(pattern, text)
print (f'Matches found: {matches}')

Matches found: ['07/09/2023']

The pattern <b>\b\d{2}\/\d{2}\/\d{4}\b</b> matches two digits, a slash, two more digits, another slash, and four digits.

## HTML Tag Removal
HTML code is full of tags, and sometimes we might want to extract just the text and discard the HTML tags. We can do this with regex using the <b>re.sub()</b> function.

In [22]:
pattern = r'<[^>]*>'
html = "<html><body>Hello, World!</body></html>"
clean_text = re.sub(pattern, '', html)
print (clean_text)

Hello, World!

The pattern <b><[^>]*></b> works as follows:

 - <b><</b> matches the opening bracket of a HTML tag.
 - <b>[^>]*</b> matches any number of characters that are not the '>' symbol.
 - <b>></b> matches the closing bracket of a HTML tag.

By applying the <b>re.sub()</b> function, we replace all matched patterns (HTML tags in this case) with an empty string, effectively removing them from the original HTML string.

These are just a few examples of how powerful and versatile regex can be in text processing tasks. With practice, you can create your own complex patterns to match virtually any text pattern you might need.

# Extracting Log Data
Logs, especially from web servers, like Apache, contain a wealth of data, and analyzing them can provide insights into user behavior, error occurrences, and potential security threats. However, this data is typically not structured, which can make it challenging to extract the precise information you need. Regular expressions (regex) offer a powerful tool for parsing these logs and extracting the specific elements of interest.

The Apache server, like many other web servers, follows a standard format for its logs. Each entry in an Apache access log provides the details of a single access event and might look something like this:

<b>127.0.0.1 - - [09/Jul/2023:14:58:59 -0700] "GET / HTTP/1.0" 200 2326</b>

Here, we can see several pieces of information:

 - The IP address of the client (127.0.0.1)
 - The date and time of the access ([09/Jul/2023:14:58:59 -0700])
 - The HTTP request method and resource requested ("GET / HTTP/1.0")
 - The status code returned (200)
 - The size of the object returned (2326 bytes)

To extract this data using regular expressions, we could write a Python script like this:

In [23]:
import re
# Define a regular expression pattern to match each element of interest
pattern = r'(?P<ip>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}) - - \[(?P<date>.*?)] "(?P<method>\w+) (?P<path>.*?) (?P<protocol>.*?)" (?P<status>\d{3}) (?P<size>\d+)'

# Sample log line
log_line = '127.0.0.1 - - [09/Jul/2023:14:58:59 -0700] "GET / HTTP/1.0" 200 2326'

# Apply the regular expression
match = re.search(pattern, log_line)

# If a match was found, print the extracted data
if match:
    print (match.groupdict())

{'ip': '127.0.0.1', 'date': '09/Jul/2023:14:58:59 -0700', 'method': 'GET', 'path': '/', 'protocol': 'HTTP/1.0', 'status': '200', 'size': '2326'}

In this script, we first define a regular expression pattern. We use the <b>(?P<name>...)<b> syntax to create named groups, which allows us to refer to the matched data by name later. The regex pattern is designed to match each element of the log line:

 - <b>\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}</b> matches the IP address, which consists of four groups of one to three digits separated by periods.
 - <b>.*?</b> in the date group matches any number of any character (non-greedy).
 - <b>\w+</b> in the method group matches one or more word characters (equivalent to [a-zA-Z0-9_]).
 - <b>.*?</b> in the path group matches any number of any character (non-greedy).
 - <b>.*?</b> in the protocol group matches any number of any character (non-greedy).
 - <b>\d{3}</b> in the status group matches exactly three digits.
 - <b>\d+</b> in the size group matches one or more digits.

Next, we use <b>re.search()</b> to search the log line for a match to the pattern. If a match is found, re.search() returns a match object, and we can use the groupdict() method to retrieve a dictionary of the named groups. This script will output:
    
    "{'ip': '127.0.0.1', 'date': '09/Jul/2023:14:58:59 -0700', 'method': 'GET', 'path': '/', 'protocol': 'HTTP/1.0', 'status': '200', 'size': '2326'}"
    
As you can see, using regular expressions allows us to easily extract the data from the log line in a structured format, making further analysis significantly easier.

# Practice Lab 3: To be handed in no later then July 14, 2025 (18:00).

Now it's your turn to practice and explore further! 

Write a Python program using one regular expression to identify potential SQL injection attempts in the following logfile. You may consider any instance where a SQL command ('s%e%l%e%c%t' in obfuscated form) followed by a hexadecimal string as a potential SQL injection attempt. The program should return the IP address and the full URL where the potential injection is found.

<b>Hint:</b> Use Python's re module and consider using lookahead and lookbehind assertions in your pattern.

Remember that cybersecurity often involves working with large datasets and logs, and knowing how to quickly parse and analyze this data is an important skill. Regular expressions can be a very useful tool for this.

This Practice Lab builds on the Practice Labs 1 and 2. In Practice Lab 1 you learned how to validate an IP address. In Practice Lab 2, you learned that it is essential to remove invalid records. It would only be fitting to verify the IP address and validate the data. However for this lab, you are to display the IP address, the Request_Url, the regular expression used, and the type of SQL attack used.

Your Python script <b>must</b> include comments.

Should you experience any challenges, kindly attach this file to an email directed to sdewitt@torontomu.ca, accompanied by a detailed description of the problem you are facing. include your full name and student number in the space provided at the top of this file.

Submissions of practice labs beyond the stipulated deadline will not be entertained, and will be awarded a grade of zero.

## Test data and explaination of each field.

### The following data was extracted as the attack occurred.

<b>Timestamp:</b> A timestamp indicates the specific date and time at which an event or activity was logged in the computer security log, often down to the millisecond, to precisely track occurrences.

<b>Source_IP:</b> The Source IP (Internet Protocol) address refers to the unique numerical label assigned to the device that initiates a digital communication, serving to identify it and locate it within a network.

<b>Destination_IP:</b> The Destination IP address is the unique numerical identifier assigned to the receiving device in a digital communication, indicating where the transmitted data is intended to go within a network.

<b>Destination_Port:</b> The Destination Port refers to the endpoint in an operating system’s networking sub-system, specified by a 16-bit number, where data packets are directed to be processed by specific protocols or applications.

<b>Filename:</b> Filename refers to the name assigned to a specific file that the threat actor is uploading.

<b>User_Agent:</b> A User Agent is a string that a browser or application sends to a web server, providing information about the software and device being used, which may include the software version, device type, and operating system.

<b>Request_Raw:</b> Request Raw typically refers to the full, unprocessed request sent to a server, including headers, payload, and other metadata, providing a detailed view of the information transmitted.

<b>X_Forwarded_For:</b> The X-Forwarded-For (XFF) header is a de-facto standard header in HTTP requests that identifies the originating IP address of a client connecting to a web server through an HTTP proxy or load balancer.


### The following data has been added post-extraction: 

<b>UnixTimestamp:</b> A Unix Timestamp represents the number of seconds that have passed since January 1, 1970, at UTC, and is commonly used to track date and time in computing.

<b>Actual_IP:</b> This likely refers to the actual IP address from which a request or event in the log originated, indicating the network address of the user or entity. Please note that threat actors will try to hide their true address (Source_IP) and was extracted from the X_Forwarded_For field.

<b>Protocol:</b> In the context of a security log, "Protocol" typically refers to the communication protocol used for transmitting data between systems, such as HTTP, HTTPS, FTP, etc.

<b>Country:</b> This indicates the country from which the request was made or the event originated, often determined by geolocating the IP address. 

<b>Country_Code:</b> A shorthand alphanumeric or numeric code representing a country, often following ISO country codes (e.g., CA for the Canada).

<b>Latitude:</b> A geographical coordinate that specifies the north–south position of a point on the Earth's surface, often used in IP geolocation to estimate the location of the user or entity. 

<b>Longitude:</b> A geographical coordinate that specifies the east-west position of a point on the Earth's surface, used alongside latitude for specifying geographical locations.

<b>ASN_Code:</b> The Autonomous System Number (ASN) Code is a unique identifier assigned to a network that engages in autonomous system routing, often indicating the network or ISP used.

<b>ASN:</b> Autonomous System Number (ASN) refers to a group of IP networks and routers under the control of a single organization that presents a common routing policy to the internet.

<b>Request_URL:</b> This was extracted from the Request_Raw data to simplify any additional processing. Understanding the specific payloads used by threat actors helps in analyzing their attack patterns and methodologies and potentially develop countermeasures or patches to prevent similar future attempts.

## Libraries used

This section loads all required libraries.

In [24]:
import re
import pandas as pd
from IPython.display import display
from urllib.parse import unquote # for url processing
from tabulate import tabulate # to display tables

In [25]:
headings = ['timestamp', 'unixTimestamp', 'source_ip', 'actual_ip', 'destination_ip', 'destination_ip_num', 'destination_port', 'protocol', 'country', 'country_code', 'Latitude', 'Longitude', 'asn_code', 'asn', 'filename', 'User_Agent', 'request_raw', 'request_url', 'X_Forwarded_For']

data = [
    ['2017-06-02 14:33:09.641', '1496413989.641', '91.247.38.57', '91.247.38.57', '192.168.10.6', '3232238086', '80', 'http', 'Ukraine', 'UA', '50.4522', '30.5287', '212496', 'GOOD SIA', 'None', 'Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/5.0.342.1 Safari/533.2', "GET /pagina.php?q=) UNION ALL SELECT NULL,'qkjvq'||'lbgvtqNPtmrAsxCRfGGzifRQBDRChGWlJOZUviYw'||'qzkjq',NULL-- Pipg HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/5.0.342.1 Safari/533.2", "/pagina.php?q=) UNION ALL SELECT NULL,'qkjvq'||'lbgvtqNPtmrAsxCRfGGzifRQBDRChGWlJOZUviYw'||'qzkjq',NULL-- Pipg", 'None'],
    ['2017-06-03 08:38:57.315', '1496479137.315', '91.247.38.57', '91.247.38.57', '192.168.10.6', '3232238086', '80', 'http', 'Ukraine', 'UA', '50.4522', '30.5287', '212496', 'GOOD SIA', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/0.2.153.0 Safari/525.19', 'GET /pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/0.2.153.0 Safari/525.19', '/pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw', 'None'],
    ['2017-06-03 08:38:57.315', '1496479137.315', '91.247.38.57', '91.247.38.57', '192.168.10.6', '3232238086', '80', 'http', 'Ukraine', 'UA', '50.4522', '30.5287', '212496', 'GOOD SIA', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/0.2.153.0 Safari/525.19', 'GET /pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US) AppleWebKit/525.19 (KHTML, like Gecko) Chrome/0.2.153.0 Safari/525.19', '/pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw', 'None'],
    ['2018-04-22 22:09:57.526', '1524434997.526', '185.153.198.252', '185.153.198.252', '192.168.10.6', '3232238086', '80', 'http', 'Ukraine', 'UA', '50.4522', '30.5287', '56380', 'it Fruit S.r.l.', 'None', 'Mozilla/5.0 ArchLinux (X11; U; Linux x86_64; en-US) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100', "GET /main.php?pref=')) WAITFOR DELAY '0:0:5' AND (('CciC'='CciC HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 ArchLinux (X11; U; Linux x86_64; en-US) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100", "/main.php?pref=')) WAITFOR DELAY '0:0:5' AND (('CciC'='CciC",  'None'],                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    ['2019-09-05 08:13:44.479', '1567671224.479', '186.148.162.100', '186.148.162.100', '192.168.10.6', '3232238086', '80', 'http', 'Colombia', 'CO', '4.6089', '-74.0943', '262186', 'TV AZTECA SUCURSAL COLOMBIA', 'None', 'Mozilla/6.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3626.109 Safari/557.36', 'GET /coppermine/themes/maze/faq.asp?cartID= and mod(29,9) union /**//**/dIsTiNcT /**//**/sElEcT 0x393631353738343330312e39,0x393631353738343330322e39,0x393631353738343330332e39,0x393631353738343330342e39,0x393631353738343330352e39,0x393631353738343330362e39,0x393631353738343330372e39,0x393631353738343330382e39,0x393631353738343330392e39,0x39363135373834333031302e39,0x39363135373834333031312e39,0x39363135373834333031322e39,0x39363135373834333031332e39,0x39363135373834333031342e39,0x39363135373834333031352e39,0x39363135373834333031362e39,0x39363135373834333031372e39,0x39363135373834333031382e39,0x39363135373834333031392e39,0x39363135373834333032302e39,0x39363135373834333032312e39,0x39363135373834333032322e39,0x39363135373834333032332e39,0x39363135373834333032342e39,0x39363135373834333032352e39,0x39363135373834333032362e39,0x39363135373834333032372e39,0x39363135373834333032382e39,0x39363135373834333032392e39,0x39363135373834333033302e39,0x39363135373834333033312e39,0x39363135373834333033322e39,0x39363135373834333033332e39,0x39363135373834333033342e39,0x39363135373834333033352e39,0x39363135373834333033362e39,0x39363135373834333033372e39 order by asc HTTP/1.1, Accept: Text/Html,Application/Xhtml Xml,Application/Xml;Q=0.9,*/*;Q=0.8, Accept-Encoding: gzip, Accept-Language: en-us,en;q=0.5, Connection: keep-alive, Host: 192.168.10.6, Referer: http://192.168.10.6/coppermine/themes/maze/faq.asp?cartID= and mod(29,9) union /**//**/dIsTiNcT /**//**/sElEcT 0x393631353738343330312e39,0x393631353738343330322e39,0x393631353738343330332e39,0x393631353738343330342e39,0x393631353738343330352e39,0x393631353738343330362e39,0x393631353738343330372e39,0x393631353738343330382e39,0x393631353738343330392e39,0x39363135373834333031302e39,0x39363135373834333031312e39,0x39363135373834333031322e39,0x39363135373834333031332e39,0x39363135373834333031342e39,0x39363135373834333031352e39,0x39363135373834333031362e39,0x39363135373834333031372e39,0x39363135373834333031382e39,0x39363135373834333031392e39,0x39363135373834333032302e39,0x39363135373834333032312e39,0x39363135373834333032322e39,0x39363135373834333032332e39,0x39363135373834333032342e39,0x39363135373834333032352e39,0x39363135373834333032362e39,0x39363135373834333032372e39,0x39363135373834333032382e39,0x39363135373834333032392e39,0x39363135373834333033302e39,0x39363135373834333033312e39,0x39363135373834333033322e39,0x39363135373834333033332e39,0x39363135373834333033342e39,0x39363135373834333033352e39,0x39363135373834333033362e39,0x39363135373834333033372e39 order by asc, User-Agent: Mozilla/6.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3626.109 Safari/557.36', '/coppermine/themes/maze/faq.asp?cartID= and mod(29,9) union /**//**/dIsTiNcT /**//**/sElEcT 0x393631353738343330312e39,0x393631353738343330322e39,0x393631353738343330332e39,0x393631353738343330342e39,0x393631353738343330352e39,0x393631353738343330362e39,0x393631353738343330372e39,0x393631353738343330382e39,0x393631353738343330392e39,0x39363135373834333031302e39,0x39363135373834333031312e39,0x39363135373834333031322e39,0x39363135373834333031332e39,0x39363135373834333031342e39,0x39363135373834333031352e39,0x39363135373834333031362e39,0x39363135373834333031372e39,0x39363135373834333031382e39,0x39363135373834333031392e39,0x39363135373834333032302e39,0x39363135373834333032312e39,0x39363135373834333032322e39,0x39363135373834333032332e39,0x39363135373834333032342e39,0x39363135373834333032352e39,0x39363135373834333032362e39,0x39363135373834333032372e39,0x39363135373834333032382e39,0x39363135373834333032392e39,0x39363135373834333033302e39,0x39363135373834333033312e39,0x39363135373834333033322e39,0x39363135373834333033332e39,0x39363135373834333033342e39,0x39363135373834333033352e39,0x39363135373834333033362e39,0x39363135373834333033372e39 order by asc', 'None'],
    ['2017-12-21 21:14:37.984', '1513890877.984', '194.28.115.112', '194.28.115.112', '192.168.10.6', '3232238086', '80', 'http', 'Netherlands', 'NL', '52.3759', '4.8975', '50968', 'Hostmaster - Ltd.', 'None', 'Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3', 'GET /head.php?corpo= AND 16=16 HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.63 Safari/534.3', '/head.php?corpo= AND 16=16', 'None'],
    ['2018-01-18 19:11:22.007', '1516302682.007', '185.92.73.172', '185.92.73.172', '192.168.10.6', '3232238086', '80', 'http', 'Netherlands', 'NL', '52.3759', '4.8975', '200904', 'Foxcloud Llp', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.9.1.10) Gecko/20100504 Firefox/3.5.10 GTB7.0 ( .NET CLR 3.5.30729)', 'GET /index.inc.php?PATH_Includes=-6428 OR 1 GROUP BY CONCAT(0x71766a7071,(SELECT (CASE WHEN (5013=5013) THEN 1 ELSE 0 END)),0x716b6b7871,FLOOR(RAND(0)*2)) HAVING MIN(0)# HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.9.1.10) Gecko/20100504 Firefox/3.5.10 GTB7.0 ( .NET CLR 3.5.30729)', '/index.inc.php?PATH_Includes=-6428 OR 1 GROUP BY CONCAT(0x71766a7071,(SELECT (CASE WHEN (5013=5013) THEN 1 ELSE 0 END)),0x716b6b7871,FLOOR(RAND(0)*2)) HAVING MIN(0)#', 'None'],
    ['2017-12-02 11:56:54.940', '1512215814.94', '185.92.73.105', '185.92.73.105', '192.168.10.6', '3232238086', '80', 'http', 'Netherlands', 'NL', '52.3759', '4.8975', '200904', 'Foxcloud Llp', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.53 Safari/534.3', "GET /sitio.php?section=;CREATE OR REPLACE FUNCTION SLEEP(int) RETURNS int AS '/lib/libc.so.6','sleep' language 'C' STRICT; SELECT sleep(5) HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.53 Safari/534.3", "/sitio.php?section=;CREATE OR REPLACE FUNCTION SLEEP(int) RETURNS int AS '/lib/libc.so.6','sleep' language 'C' STRICT; SELECT sleep(5)", 'None'],
    ['2017-12-02 11:56:55.173', '1512215815.173', '185.92.73.105', '185.92.73.105', '192.168.10.6', '3232238086', '80', 'http', 'Netherlands', 'NL', '52.3759', '4.8975', '200904', 'Foxcloud Llp', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.53 Safari/534.3', 'GET /sitio.php?section= AND 3164=(SELECT 3164 FROM PG_SLEEP(5)) HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/534.3 (KHTML, like Gecko) Chrome/6.0.472.53 Safari/534.3', '/sitio.php?section= AND 3164=(SELECT 3164 FROM PG_SLEEP(5))', 'None'],
    ['2017-06-25 20:07:19.749', '1498421239.749', '91.247.38.57', '91.247.38.57', '192.168.10.6', '3232238086', '80', 'http', 'Ukraine', 'UA', '50.4522', '30.5287', '212496', 'GOOD SIA', 'None', 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0b6pre) Gecko/20100903 Firefox/4.0b6pre', 'GET /pagina.php?q= AND 7325=7325-- aiHA HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-15,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip,deflate, Accept-Language: en-us,en;q=0.5, Cache-Control: no-cache,no-store, Connection: close, Host: 192.168.10.6, Pragma: no-cache, User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:2.0b6pre) Gecko/20100903 Firefox/4.0b6pre', '/pagina.php?q= AND 7325=7325-- aiHA', 'None'],
    ['2019-10-09 12:10:26.801', '1570623026.801', '125.161.104.170', '10.0.10.255', '192.168.10.6', '3232238086', '80', 'http', 'Indonesia', 'ID', '-6.1741', '106.8296', '7713', 'PT Telekomunikasi Indonesia', 'None', 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727), X-Cnection: Close, X-Forwarded-For: 10.0.10.255', 'GET /scripts/page.php?sivu=9999 union all select null-- HTTP/1.1, Accept: */*, Cache-Control: max-stale=0, Connection: Keep-Alive, Host: 192.168.10.6, User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727), X-Cnection: Close, X-Forwarded-For: 10.0.10.255', '/scripts/page.php?sivu=9999 union all select null--', '10.0.10.255'],
    ['2019-10-09 12:10:27.703', '1570623027.703', '125.161.104.170', '10.0.10.255', '192.168.10.6', '3232238086', '80', 'http', 'Indonesia', 'ID', '-6.1741', '106.8296', '7713', 'PT Telekomunikasi Indonesia', 'None', 'Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727), X-Cnection: Close, X-Forwarded-For: 10.0.10.255', "GET /axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0 HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip, Accept-Language: en-us,en;q=0.5, Cache-Control: max-stale=0, Connection: Keep-Alive, Host: 192.168.10.6, Referer: http://192.168.10.6/axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729), Via: 1.1 103.28.148.242 (Mikrotik HttpProxy), X-Bluecoat-Via: b29e38a0dcbe4d83, X-Forwarded-For: 10.22.2.1, X-Proxy-Id: 1949884598", '/scripts/page.php?sivu= and db_name()))<32', '10.0.10.255'],
    ['2019-09-16 01:59:08.629', '1568599148.629', '180.244.136.168', '10.22.2.1', '192.168.10.6', '3232238086', '80', 'http', 'Indonesia', 'ID', '-6.9217', '107.6071', '7713', 'PT Telekomunikasi Indonesia', 'None', 'Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729), Via: 1.1 103.28.148.242 (Mikrotik HttpProxy), X-Bluecoat-Via: b29e38a0dcbe4d83, X-Forwarded-For: 10.22.2.1, X-Proxy-Id: 1949884598', "GET /axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0 HTTP/1.1, Accept: text/html,application/xhtml xml,application/xml;q=0.9,*/*;q=0.8, Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7, Accept-Encoding: gzip, Accept-Language: en-us,en;q=0.5, Cache-Control: max-stale=0, Connection: Keep-Alive, Host: 192.168.10.6, Referer: http://192.168.10.6/axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0, User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; pt-PT; rv:1.9.1.2) Gecko/20090729 Firefox/3.5.2 (.NET CLR 3.5.30729), Via: 1.1 103.28.148.242 (Mikrotik HttpProxy), X-Bluecoat-Via: b29e38a0dcbe4d83, X-Forwarded-For: 10.22.2.1, X-Proxy-Id: 1949884598", "/axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0'", '10.22.2.1, X-Proxy-Id: 1949884598'],
    ['2019-10-30 07:43:52.468', '1572421432.468', '52.138.22.120', '10.240.255.55', '192.168.10.6', '3232238086', '80', 'http', 'Canada', 'CA', '43.6655', '-79.4204', '8075', 'MICROSOFT-CORP-MSN-AS-BLOCK', 'None', 'Mozilla/6.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3626.109 Safari/557.36, Via: 1.1 wk-caas-40df62fe72084675bb8adf2a99875bc5-22c5fd691034103108211f (squid/3.5.12), X-Forwarded-For: 10.240.255.55', "GET /8003/tekst.php?idt=' and /**//**/cOnVeRt(int,(char(63)+char(126)+char(33)+(char(65)+char(57)+char(54)+char(49)+char(53)+char(67)+char(55)+char(56)+char(52)+char(51)+char(48)+char(68))+char(63)+char(126)+char(33))) and '1'='1 HTTP/1.1, Accept: Text/Html,Application/Xhtml Xml,Application/Xml;Q=0.9,*/*;Q=0.8, Accept-Encoding: gzip, Accept-Language: en-us,en;q=0.5, Cache-Control: max-age=0, Connection: keep-alive, Host: 192.168.10.6, Referer: http://192.168.10.6/8003/tekst.php?idt=' and /**//**/cOnVeRt(int,(char(63)+char(126)+char(33)+(char(65)+char(57)+char(54)+char(49)+char(53)+char(67)+char(55)+char(56)+char(52)+char(51)+char(48)+char(68))+char(63)+char(126)+char(33))) and '1'='1, User-Agent: Mozilla/6.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3626.109 Safari/557.36, Via: 1.1 wk-caas-40df62fe72084675bb8adf2a99875bc5-22c5fd691034103108211f (squid/3.5.12), X-Forwarded-For: 10.240.255.55", "/8003/tekst.php?idt=' and /**//**/cOnVeRt(int,(char(63)+char(126)+char(33)+(char(65)+char(57)+char(54)+char(49)+char(53)+char(67)+char(55)+char(56)+char(52)+char(51)+char(48)+char(68))+char(63)+char(126)+char(33))) and '1'='1'", '10.240.255.55']
]

### Converting the list to a DataFrame

In [26]:

#converting to dataframe
df = pd.DataFrame(data, columns=headings)

#option to display full lines
pd.set_option('display.max_colwidth', None)

#extracting the columns where user input is received
#filename could have an sqli as it is user input and user input should not be trusted
#the file content lies beyond the scope of this lab as per my understanding
vuln_columns = df[['filename', 'request_raw']]

### Define regex here
Create one regular expression that will detect all attacks.

In [27]:
#defining SQL instructions to watch for
#SQL INSTRUCTIONS (https://www.w3schools.com/SQL/sql_ref_keywords.asp)
keywords = [
    "ADD", "ADD CONSTRAINT", "ALL", "ALTER", "ALTER COLUMN", "ALTER TABLE", "AND",
    "ANY", "AS", "ASC", "BACKUP DATABASE", "BETWEEN", "CASE", "CHECK", "COLUMN",
    "CONSTRAINT", "CREATE", "CREATE DATABASE", "CREATE INDEX", "CREATE OR REPLACE VIEW",
    "CREATE TABLE", "CREATE PROCEDURE", "CREATE UNIQUE INDEX", "CREATE VIEW", "DATABASE",
    "DEFAULT", "DELETE", "DESC", "DISTINCT", "DROP", "DROP COLUMN", "DROP CONSTRAINT",
    "DROP DATABASE", "DROP DEFAULT", "DROP INDEX", "DROP TABLE", "DROP VIEW", "EXEC",
    "EXISTS", "FOREIGN KEY", "FROM", "FULL OUTER JOIN", "GROUP BY", "HAVING", "IN",
    "INDEX", "INNER JOIN", "INSERT INTO", "INSERT INTO SELECT", "IS NULL", "IS NOT NULL",
    "JOIN", "LEFT JOIN", "LIKE", "LIMIT", "NOT", "NOT NULL", "OR", "ORDER BY",
    "OUTER JOIN", "PRIMARY KEY", "PROCEDURE", "RIGHT JOIN", "ROWNUM", "SELECT",
    "SELECT DISTINCT", "SELECT INTO", "SELECT TOP", "SET", "TABLE", "TOP",
    "TRUNCATE TABLE", "UNION", "UNION ALL", "UNIQUE", "UPDATE", "VALUES", "VIEW",
    "WHERE"
]

#These words are also used to trick the backend into processing an sql query
keywords.extend(["CONVERT", "CHAR", "INT"])

## 1 - normalizing case. could also pass re.I with the pattern
vuln_columns = vuln_columns.map(str.lower)

## 2 - sanitizing any special character used to escape context which could be a sign of sqli
special_chars = [
    r"'", r'"', r';', r'\*', r'/\*', r'--', r'#', ',', '//'
]
pattern = "|".join(special_chars)
vuln_columns = vuln_columns.map(lambda x: re.sub(pattern, '', x))

## 3 - decoding url encoded expressions, these could be legitimate requests so we will still run our regex on them
url_pattern = r"/.*%[a-fA-F0-9]{2}.*?\b"
urls = vuln_columns.map(lambda x: re.findall(url_pattern, x))
urls = urls.map(lambda x: list(map(unquote,x)))
#display(urls)

## 4 - catching hexadecimal expressions
hex_pattern = r"0x[a-fA-F0-9]+"
hex_expressions = vuln_columns.map(lambda x: re.findall(hex_pattern, x)) 
#display(hex_expressions)

## 5 - detecting tautology with lookahead
t_pattern = r"(.+)=(?=\1)"
tautology = vuln_columns.map(lambda x: re.findall(t_pattern, x))
#display(tautology)

## 6 - using the keywords to detect any instructions in the decoded urls or the original requests
sqli_pattern = r'\b(?:' + '|'.join(map(re.escape, keywords)) + r')\b'
injection_instruction = vuln_columns.map(lambda x: re.findall(sqli_pattern, x, re.I))
#display(injection_instruction)

encoded_instruction = urls.map(
    lambda matches: [kw for s in matches for kw in re.findall(sqli_pattern, s, re.I)]
)
#display(encoded_instruction)

### Main section

This code will add a new column to the dataframe called 'sql_injection', which will be True if the request_raw contains any of the patterns that match the regular expression for SQL injections.

In [28]:
## 7 - summarizing our findings
df['sql_injection'] = (
    hex_expressions.map(bool).any(axis=1) |
    tautology.map(bool).any(axis=1) |
    injection_instruction.map(bool).any(axis=1) |
    encoded_instruction.map(bool).any(axis=1)
)
#display(df)

### Display rows flagged as SQL injections

Display only the IP address, the request_Url, the regular expression used, and the type of SQL attack(s) used.

In [29]:

## 8 - displaying more information
df['sqli_flag_source'] = [
    ', '.join(filter(None, [
        'Alternative Encoding (Hex)' if any(hex_expressions.iloc[i]) else None,
        'Tautology Injection' if any(tautology.iloc[i]) else None,
        'SQL Keyword Injection' if any(injection_instruction.iloc[i]) else None,
        'Encoded SQL Keywords' if any(encoded_instruction.iloc[i]) and any(injection_instruction.iloc[i]) else None
    ]))
    or None
    for i in range(len(df))
]
flagged_df = df[df['sqli_flag_source'].notna()]

regex_map = [
    (hex_pattern, "Alternative Encoding SQL Injection (Hexadecimal)"),
    (t_pattern, "Tautology-Based SQL Injection"),
    (sqli_pattern, "Union-Based / Error-Based / In-Band SQL Injection"),
    (url_pattern, "Alternative Encoding SQL Injection (URL Encoded)"),
]


table = [["Regex Pattern", "SQL Injection Type"]] + regex_map

display(flagged_df[['actual_ip', 'request_url', 'sqli_flag_source']])
#doesn't display properly
#display(tabulate(table, headers="firstrow", tablefmt="grid"))
regex_df = pd.DataFrame(regex_map, columns=["Regex Pattern", "SQL Injection Type"])
display(regex_df)

#resources used: 
#https://regex101.com/
#help function in python

,actual_ip,request_url,sqli_flag_source
0,91.247.38.57,"/pagina.php?q=) UNION ALL SELECT NULL,'qkjvq'||'lbgvtqNPtmrAsxCRfGGzifRQBDRChGWlJOZUviYw'||'qzkjq',NULL-- Pipg",SQL Keyword Injection
1,91.247.38.57,"/pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw","Alternative Encoding (Hex), SQL Keyword Injection"
2,91.247.38.57,"/pagina.php?q=) UNION ALL SELECT NULL,NULL,CONCAT(0x71786b7671,0x634668477149734447774d5065564b636b6e554d7676494768424f5761665668574464456449434a,0x716a7a6271)-- gaEw","Alternative Encoding (Hex), SQL Keyword Injection"
3,185.153.198.252,/main.php?pref=')) WAITFOR DELAY '0:0:5' AND (('CciC'='CciC,"Tautology Injection, SQL Keyword Injection"
4,186.148.162.100,"/coppermine/themes/maze/faq.asp?cartID= and mod(29,9) union /**//**/dIsTiNcT /**//**/sElEcT 0x393631353738343330312e39,0x393631353738343330322e39,0x393631353738343330332e39,0x393631353738343330342e39,0x393631353738343330352e39,0x393631353738343330362e39,0x393631353738343330372e39,0x393631353738343330382e39,0x393631353738343330392e39,0x39363135373834333031302e39,0x39363135373834333031312e39,0x39363135373834333031322e39,0x39363135373834333031332e39,0x39363135373834333031342e39,0x39363135373834333031352e39,0x39363135373834333031362e39,0x39363135373834333031372e39,0x39363135373834333031382e39,0x39363135373834333031392e39,0x39363135373834333032302e39,0x39363135373834333032312e39,0x39363135373834333032322e39,0x39363135373834333032332e39,0x39363135373834333032342e39,0x39363135373834333032352e39,0x39363135373834333032362e39,0x39363135373834333032372e39,0x39363135373834333032382e39,0x39363135373834333032392e39,0x39363135373834333033302e39,0x39363135373834333033312e39,0x39363135373834333033322e39,0x39363135373834333033332e39,0x39363135373834333033342e39,0x39363135373834333033352e39,0x39363135373834333033362e39,0x39363135373834333033372e39 order by asc","Alternative Encoding (Hex), SQL Keyword Injection"
5,194.28.115.112,/head.php?corpo= AND 16=16,"Tautology Injection, SQL Keyword Injection"
6,185.92.73.172,"/index.inc.php?PATH_Includes=-6428 OR 1 GROUP BY CONCAT(0x71766a7071,(SELECT (CASE WHEN (5013=5013) THEN 1 ELSE 0 END)),0x716b6b7871,FLOOR(RAND(0)*2)) HAVING MIN(0)#","Alternative Encoding (Hex), Tautology Injection, SQL Keyword Injection"
7,185.92.73.105,"/sitio.php?section=;CREATE OR REPLACE FUNCTION SLEEP(int) RETURNS int AS '/lib/libc.so.6','sleep' language 'C' STRICT; SELECT sleep(5)",SQL Keyword Injection
8,185.92.73.105,/sitio.php?section= AND 3164=(SELECT 3164 FROM PG_SLEEP(5)),SQL Keyword Injection
9,91.247.38.57,/pagina.php?q= AND 7325=7325-- aiHA,"Tautology Injection, SQL Keyword Injection"
10,10.0.10.255,/scripts/page.php?sivu=9999 union all select null--,SQL Keyword Injection
11,10.0.10.255,/scripts/page.php?sivu= and db_name()))<32,"Alternative Encoding (Hex), Tautology Injection, SQL Keyword Injection"
12,10.22.2.1,"/axis-cgi/servlet/itemdetails.asp?catalogid=999999.9' /**/uNiOn/**/aLl /**/sElEcT 0x393133353134353632312e39,0x393133353134353632322e39,0x393133353134353632332e39,0x393133353134353632342e39,0x393133353134353632352e39,0x393133353134353632362e39,0x393133353134353632372e39,0x393133353134353632382e39,0x393133353134353632392e39,0x39313335313435363231302e39,0x39313335313435363231312e39,0x39313335313435363231322e39,0x39313335313435363231332e39,0x39313335313435363231342e39,0x39313335313435363231352e39,0x39313335313435363231362e39,0x39313335313435363231372e39,0x39313335313435363231382e39,0x39313335313435363231392e39,0x39313335313435363232302e39,0x39313335313435363232312e39,0x39313335313435363232322e39,0x39313335313435363232332e39,0x39313335313435363232342e39,0x39313335313435363232352e39,0x39313335313435363232362e39,0x39313335313435363232372e39,0x39313335313435363232382e39 and '0'='0'","Alternative Encoding (Hex), Tautology Injection, SQL Keyword Injection"
13,10.240.255.55,"/8003/tekst.php?idt=' and /**//**/cOnVeRt(int,(char(63)+char(126)+char(33)+(char(65)+char(57)+char(54)+char(49)+char(53)+char(67)+char(55)+char(56)+char(52)+char(51)+char(48)+char(68))+char(63)+char(126)+char(33))) and '1'='1'","Tautology Injection, SQL Keyword Injection"

,Regex Pattern,SQL Injection Type
0,0x[a-fA-F0-9]+,Alternative Encoding SQL Injection (Hexadecimal)
1,(.+)=(?=\1),Tautology-Based SQL Injection
2,\b(?:ADD|ADD\ CONSTRAINT|ALL|ALTER|ALTER\ COLUMN|ALTER\ TABLE|AND|ANY|AS|ASC|BACKUP\ DATABASE|BETWEEN|CASE|CHECK|COLUMN|CONSTRAINT|CREATE|CREATE\ DATABASE|CREATE\ INDEX|CREATE\ OR\ REPLACE\ VIEW|CREATE\ TABLE|CREATE\ PROCEDURE|CREATE\ UNIQUE\ INDEX|CREATE\ VIEW|DATABASE|DEFAULT|DELETE|DESC|DISTINCT|DROP|DROP\ COLUMN|DROP\ CONSTRAINT|DROP\ DATABASE|DROP\ DEFAULT|DROP\ INDEX|DROP\ TABLE|DROP\ VIEW|EXEC|EXISTS|FOREIGN\ KEY|FROM|FULL\ OUTER\ JOIN|GROUP\ BY|HAVING|IN|INDEX|INNER\ JOIN|INSERT\ INTO|INSERT\ INTO\ SELECT|IS\ NULL|IS\ NOT\ NULL|JOIN|LEFT\ JOIN|LIKE|LIMIT|NOT|NOT\ NULL|OR|ORDER\ BY|OUTER\ JOIN|PRIMARY\ KEY|PROCEDURE|RIGHT\ JOIN|ROWNUM|SELECT|SELECT\ DISTINCT|SELECT\ INTO|SELECT\ TOP|SET|TABLE|TOP|TRUNCATE\ TABLE|UNION|UNION\ ALL|UNIQUE|UPDATE|VALUES|VIEW|WHERE|CONVERT|CHAR|INT)\b,Union-Based / Error-Based / In-Band SQL Injection
3,/.*%[a-fA-F0-9]{2}.*?\b,Alternative Encoding SQL Injection (URL Encoded)

Remember, regex syntax can vary a bit between languages, so always check the specific syntax for the language you are using. Practice and patience will make you proficient in writing and understanding regex patterns. Happy coding!

# This concludes your third lesson on the path to cyber security analysis using Python.